apiVersion: v1
kind: Service
metadata:
  name: chromadb-service
  namespace: hotel-ai
  labels:
    app: chromadb
spec:
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: chromadb
  type: ClusterIP
