apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: hotel-ai
  labels:
    app: backend
spec:
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: backend
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: hotel-ai
  labels:
    app: frontend
spec:
  ports:
    - port: 8501
      targetPort: 8501
      protocol: TCP
      nodePort: 30501
      name: http
  selector:
    app: frontend
  type: NodePort
